### ISSUE TITLE
[BUG] README is difficult to read in Dark Mode

### ISSUE THREAD

**Issue by Pyxxil** [Matteas-Eden/Matteas-Eden#1]
With the Beta release for Dark Mode on GitHub it makes this README rather difficult to read (see below screenshot).

Fixing this would be beneficial as it would allow people to more easily view the README.

<img width="904" alt="Reading Difficulties in Dark Mode" src="https://user-images.githubusercontent.com/12526499/103266605-d3e91000-4a14-11eb-88e4-d71d51df7a29.png">

**Comment by Matteas-Eden** [comment]
Thanks for pointing this out. I agree, it is difficult to read in dark mode and given that it was originally designed for light mode this doesn't even come as much of a surprise. However, without support for theme context during the beta it's not something I can fix without drastically redesigning the README.

Good news is, [GitHub knows about it](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/5) and so I expect a fix to come *eventually*. Until then, the README will remain unchanged. Sorry :(

**Comment by Pyxxil** [comment]
Sure, but there are definitely work arounds you could do until the theme support arrives, such as:
- SVG's support text and styling, and also scale better to displays (which is something I believe you're interested in too).
- Surround the unreadable images with a background (in something like GIMP, not with CSS) that's white (akin to the light mode of Github), or some neutral colour.

Just my two cents for if you want to do something about it in the meantime. Otherwise, I may as well close this issue.

**Comment by Matteas-Eden** [comment]
On that first point, although SVGs do have advantages I don't see how replacing some of the current PNGs with SVGs would address the issue raised.

On that second point, yes I could add white backgrounds to those images which do not have them, but ultimately it would only serve to make it *readable* in dark mode, but not *good*. Which I suppose is an improvement...
